In [1]:
pip install torch===1.5.0 torchvision===0.6.0 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
t

array([0., 1., 2., 3., 4., 5., 6.])

In [5]:
t.ndim

1

In [6]:
t.shape

(7,)

In [7]:
t[0], t[1], t[6]

(0.0, 1.0, 6.0)

In [8]:
t[2:5], t[4:-1]

(array([2., 3., 4.]), array([4., 5.]))

In [9]:
t[:2], t[3:]

(array([0., 1.]), array([3., 4., 5., 6.]))

In [10]:
t = np.array(
  [
    [1.,2.,3.],
    [4.,5.,6.],
    [7.,8.,9.],
    [10.,11.,12.]
  ]
)

In [11]:
t.ndim

2

In [12]:
t.shape

(4, 3)

In [3]:
import torch

In [14]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.,])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [15]:
t.dim()

1

In [16]:
t.shape, t.size

(torch.Size([7]), <function Tensor.size>)

In [17]:
t[2:5], t[4:-1]

(tensor([2., 3., 4.]), tensor([4., 5.]))

In [18]:
t[:2], t[3:]

(tensor([0., 1.]), tensor([3., 4., 5., 6.]))

In [19]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [20]:
t.size()

torch.Size([4, 3])

In [21]:
t[:,1]

tensor([ 2.,  5.,  8., 11.])

In [22]:
t[:,:-1]

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])

#### 브로드캐스팅(Broadcasting)

In [23]:
m1 = torch.FloatTensor([[3,3]])

In [24]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [27]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])  # 연산을 하려면 2차원이 되야해서 [3,3]으로 자동변환
m1 + m2

tensor([[4., 5.]])

In [28]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
m1 + m2

tensor([[4., 5.],
        [5., 6.]])

In [29]:
#요소의 크기를 맞추기 위해 
# [1,2] -> [1,2],[1,2]
# [3],[4] -> [3,3],[4,4] 
#내부적으로 변환됨

#### 행렬의 곱셈

In [30]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

In [31]:
m1.mul(m2)

tensor([[1., 2.],
        [6., 8.]])

In [33]:
t = torch.FloatTensor([[1, 2], [3, 4]])
t.mean()

tensor(2.5000)

In [35]:
t.mean(dim=0)  # 행방향

tensor([2., 3.])

t.sum(dim=0

In [4]:
import numpy as np
import torch

In [5]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])

In [6]:
ft = torch.FloatTensor(t)

In [8]:
ft.shape

torch.Size([2, 2, 3])

3차원을 2차원으로 바꾸려함

In [9]:
ft.view([-1,3])  #3열을 만들고 나머지는 임의로 계산

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

4 * 3 행렬로 변환

#### 스퀴즈(Squeeze) - 1인 차원을 제거

In [10]:
ft = torch.FloatTensor([[0],[1],[2]])
ft.shape

torch.Size([3, 1])

In [11]:
ft.squeeze()  #1차원으로 변함

tensor([0., 1., 2.])

In [13]:
ft.unsqueeze(0)   #0 -> 행방향에 차원추가    1-> 열방향에 차원추가

tensor([[[0.],
         [1.],
         [2.]]])

In [14]:
ft.shape

torch.Size([3, 1])

In [15]:
x = torch.FloatTensor([[1,2],
                       [3,4]])
y = torch.FloatTensor([[5,6],
                       [7,8]])

In [16]:
torch.cat([x,y],dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [17]:
torch.cat([x,y],dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [19]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [20]:
torch.stack([x,y,z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [21]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])

In [22]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [23]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [25]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [26]:
x.mul(2.)

tensor([[2., 4.],
        [6., 8.]])